name: Haus Annerl
favicon: null
layout_spectrum: 0.21563885547220707
typography_spectrum: 0.5065156095661223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6179110677912831
  lightness: 0.1131336442194879
  saturation: 0.3723433695267886
  rhythmicContrast: 0.6123787465039641
purpose: []
